In [164]:
import pandas as pd
import requests
import http.client
import json

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=IND", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=CHN", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [171]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=ITA", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=ESP", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=USA", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=GBR", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=BRA", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=BRA", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=FRA", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=DEU", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=JPN", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=KOR", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=KOR", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=PAK", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [ ]:
#headers = {
 #   'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
  #  'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
#}
#conn.request("GET", "/provinces?iso=BGD", headers=headers)
#res = conn.getresponse()
#data = res.read()

#print(data.decode("utf-8"))

In [256]:
conn = http.client.HTTPSConnection("covid-19-statistics.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "ab8cd74ce5msha3a4f3decdc126ap1accf1jsnfdaa84a503eb",
    'x-rapidapi-host': "covid-19-statistics.p.rapidapi.com"
}

conn.request("GET", "/provinces?iso=AUS", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"data":[{"iso":"AUS","name":"Australia","province":"","lat":null,"long":null},{"iso":"AUS","name":"Australia","province":"Australian Capital Territory","lat":"-35.4735","long":"149.0124"},{"iso":"AUS","name":"Australia","province":"External territories","lat":null,"long":null},{"iso":"AUS","name":"Australia","province":"From Diamond Princess","lat":"35.4437","long":"139.6380"},{"iso":"AUS","name":"Australia","province":"Jervis Bay Territory","lat":null,"long":null},{"iso":"AUS","name":"Australia","province":"New South Wales","lat":"-33.8688","long":"151.2093"},{"iso":"AUS","name":"Australia","province":"Northern Territory","lat":"-12.4634","long":"130.8456"},{"iso":"AUS","name":"Australia","province":"Queensland","lat":"-28.0167","long":"153.4000"},{"iso":"AUS","name":"Australia","province":"South Australia","lat":"-34.9285","long":"138.6007"},{"iso":"AUS","name":"Australia","province":"Tasmania","lat":"-41.4545","long":"145.9707"},{"iso":"AUS","name":"Australia","province":"Victoria","lat":"-37.8136","long":"144.9631"},{"iso":"AUS","name":"Australia","province":"Western Australia","lat":"-31.9505","long":"115.8605"}]}

In [257]:


# Since data already has the response bytes, decode and load them directly as JSON
json_payload = json.loads(data.decode('utf-8'))

# Extract the nested 'data' list and structure it as a clean DataFrame
df = pd.DataFrame(json_payload['data'])
df.head()

   iso       name                      province       lat      long
0  AUS  Australia                                    None      None
1  AUS  Australia  Australian Capital Territory  -35.4735  149.0124
2  AUS  Australia          External territories      None      None
3  AUS  Australia         From Diamond Princess   35.4437  139.6380
4  AUS  Australia          Jervis Bay Territory      None      None

In [235]:
#df.to_csv("italy_covid-19")

In [ ]:
#df.to_csv("india_covid-19")

In [236]:
#df.to_csv("italy_covid-19")

In [ ]:
#df.to_csv("Spain_covid-19")

In [187]:
#df.to_csv("United_Kingdom__covid-19")

In [194]:
#df.to_csv("Brazil_covid-19")

In [ ]:
#df.to_csv("Russia_covid-19")

In [ ]:
#df.to_csv("France_covid-19")

In [ ]:
#df.to_csv("Germany_covid-19")

In [ ]:
#df.to_csv("South Korea_covid-19")

In [ ]:
#df.to_csv("Bangladesh_covid-19")

In [ ]:
#df.to_csv("Pakistan_covid-19")

In [ ]:
#df.to_csv("Australia_covid-19")

In [258]:
#df.to_csv("Australia_covid-19")

In [280]:
df1 = pd.read_csv('/content/Brazil_covid-19')

In [281]:
df2 = pd.read_csv('/content/China_covid-19')

In [282]:
df3 = pd.read_csv('/content/France_covid-19')

In [283]:
df4 = pd.read_csv('/content/Germany_covid-19')

In [284]:
df5 = pd.read_csv('/content/Japan_covid-19')

In [285]:
df6 = pd.read_csv('/content/Korea_covid-19')

In [286]:
df7 = pd.read_csv('/content/Russia_covid-19')

In [287]:
df8 = pd.read_csv('/content/Spain_covid-19')

In [288]:
df9 = pd.read_csv('/content/United States_covid-19')

In [289]:
df10 = pd.read_csv('/content/United_Kingdom__covid-19')

In [290]:
df11 = pd.read_csv('/content/india_covid-19')

In [291]:
df12 = pd.read_csv('/content/italy_covid-19')

In [292]:
df13 = pd.read_csv('/content/Australia_covid-19')

In [260]:
df.head(5)

   Unnamed: 0  iso       name                      province      lat      long
0           0  AUS  Australia                           NaN      NaN       NaN
1           1  AUS  Australia  Australian Capital Territory -35.4735  149.0124
2           2  AUS  Australia          External territories      NaN       NaN
3           3  AUS  Australia         From Diamond Princess  35.4437  139.6380
4           4  AUS  Australia          Jervis Bay Territory      NaN       NaN

In [261]:
df.shape

(12, 6)

In [294]:
final_df = pd.concat([df1, df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13], ignore_index=True)

print(final_df.shape)

(552, 6)

In [295]:
final_df.to_csv("combined_data.csv", index=False)

In [297]:
main_data=pd.read_csv('/content/combined_data.csv')
main_data.head()

   Unnamed: 0  iso    name  province      lat     long
0           0  BRA  Brazil       NaN -14.2350 -51.9253
1           1  BRA  Brazil      Acre  -9.0238 -70.8120
2           2  BRA  Brazil   Alagoas  -9.5713 -36.7820
3           3  BRA  Brazil     Amapa   0.9020 -52.0030
4           4  BRA  Brazil  Amazonas  -3.4168 -65.8561

In [298]:
main_data.shape

(552, 6)